### ISSUE TITLE
REMOVE should have a 'D' appended to it

### ISSUE THREAD

**Issue by stowellt** [Dilatorily/packery-angular#3]
In packery-angular.js, Line 249:
` REMOVE: 'removeComplete'` should be:
`REMOVED: 'removeComplete'`

to match line 510

and line 251:
`REMOVE: '$paRemoveComplete'` should be:
`REMOVED: '$paRemoveComplete'`

to match line 526

**Comment by Dilatorily** [comment]
Thanks for your report. It is fixed in v1.0.1!
