### ISSUE TITLE
Unable to add items with  $timeout(initializePackery);

### ISSUE THREAD

**Issue by stowellt** [Dilatorily/packery-angular#4]
I found that I had to change line 310 from:
` $timeout(initializePackery);`

to:
` initializePackery();`

or else when the link function for the PackeryItemDirective runs, this check fails:
```
  if (controller.packery) {
                controller.add(element[0]);
            }

```
and controller.add() is never called. Thanks for any help

**Comment by Dilatorily** [comment]
Do you have a sample project to reproduce it?

The `$timeout` is there to wait for the next digest loop and insure that Angular has rendered the child elements.

**Comment by stowellt** [comment]
I think I figured out what was causing it. To reproduce it, try adding an ng-if to a pa-packery element, i.e.:

```
<pa-packery pa-options="options" ng-if="condition">
    <pa-packery-item class="pa-item">Sample item 1</pa-packery-item>
    <pa-packery-item class="pa-item">Sample item 2</pa-packery-item>
    <pa-packery-item class="pa-item">Sample item 3</pa-packery-item>
</pa-packery>
```
The issue is once ng-if evaluates to true, the pa-packery-items are evaluated before pa-packery has fully initialized, and so are never added to the controller.

**Comment by Dilatorily** [comment]
Indeed, using a `ng-if` on a `pa-packery` element would change the digest loop.

You can either wrap the `pa-packery` element in a div or use `ng-show`.

```
<div ng-if="condition">
  <pa-packery pa-options="options">
    <pa-packery-item class="pa-item">Sample item 1</pa-packery-item>
    <pa-packery-item class="pa-item">Sample item 2</pa-packery-item>
    <pa-packery-item class="pa-item">Sample item 3</pa-packery-item>
  </pa-packery>
</div>

<pa-packery pa-options="options" ng-show="condition">
  <pa-packery-item class="pa-item">Sample item 1</pa-packery-item>
  <pa-packery-item class="pa-item">Sample item 2</pa-packery-item>
  <pa-packery-item class="pa-item">Sample item 3</pa-packery-item>
</pa-packery>
```

For now, I'll add some notes in the README to avoid similar issues in the future.

**Comment by stowellt** [comment]
sounds good, thanks

**Comment by stowellt** [comment]
Actually I tried wrapping pa-packery in a div with ng-if but that still didn't work. I think it would need to be ng-show instead

**Comment by Dilatorily** [comment]
I tried reproducing your issue with `ng-if`. Even putting a `ng-if` on the `pa-packery` element is working fine on my side.

Can you tell me what is the console output if you add `console.log($element[0]);` to line 425?

**Comment by stowellt** [comment]
The console.log output shows the `<pa-packery> ` element
