### ISSUE TITLE
Resizing of a packery-item

### ISSUE THREAD

**Issue by chennas** [Dilatorily/packery-angular#5]
Hi,

Can you please let me know, whether this directive supports the following functionalities.

1. Resizing of an packery-item 
2. Removing of the item, and can we have a example for this.

Thanks in advance.

**Comment by Dilatorily** [comment]
1. You should be able to change the CSS of a `packery-item` to resize your element.
The Packery instance will likely be out of sync, so you'll need to call the [`layout()`](http://packery.metafizzy.co/methods.html#layout-packery) method from it. To get the Packery instance, you can listen to the `$paEvents.INITIALIZED` event.

```html
<pa-packery pa-options="options">
  <pa-packery-item ng-style="variableStyle">Sample item</pa-packery-item>
</pa-packery>
```

```javascript
var packeryInstance = null;
$scope.$on($paEvents.INITIALIZED, function (event, hash, packery) {
  packeryInstance = packery;
});

// ...
// When you change `variableStyle`
packeryInstance.layout();
```

2. To remove an item, you just need to destroy the `packery-item`. This is an example using `ng-repeat`.

```html
<pa-packery pa-options="options">
  <pa-packery-item ng-repeat="item in items" ng-style="item.style">{{item.content}}</pa-packery-item>
</pa-packery>
```

```javascript
$scope.items = [
  {
    content: 'Item 1',
    style: { color: 'red' }
  }, {
    content: 'Item 2',
    style: { color: 'green' }
  }, {
    content: 'Item 3',
    style: { color: 'blue' }
  }
];

// When you want to remove your item
$scope.items.splice(1, 1);
```

I hope it helps!

**Comment by chennas** [comment]
Hi ,
Thanks for your quick reply.
Regarding the resizing, I want the end user to play with the items, like increasing and decreasing the size of the each item.
When your change the 'variableStyle' it will be static right, I want the resizing to be dynamic at the run time.

**Comment by Dilatorily** [comment]
This is out of scope of the library. This is an AngularJS wrapper around [Packery](http://packery.metafizzy.co/).

You can have the `variableStyle` to be changed with a [`DragEvent`](https://developer.mozilla.org/en-US/docs/Web/API/DragEvent) to have dynamic resizing.

**Comment by chennas** [comment]
Ok, Thanks for the reply. I will try it from my end.

**Comment by chennas** [comment]
Hi , I tried to follow as below, but he packeryInstance is coming as a number, and [packeryInstance.layout();] is not working as said.

var packeryInstance = null;
$scope.$on($paEvents.INITIALIZED, function (hash, packery) {
  **packeryInstance** = packery;
});

// ...
// When you change `variableStyle`
packeryInstance.layout();

**Comment by Dilatorily** [comment]
@chennas Sorry, I remembered the API for `$scope.$on` incorrectly.
The snippet should read:
```javascript
var packeryInstance = null;
$scope.$on($paEvents.INITIALIZED, function (event, hash, packery) {
  packeryInstance = packery;
});

// ...
// When you change `variableStyle`
packeryInstance.layout();
```

**Comment by chennas** [comment]
Hi, Thanks for the reply, it worked.

I have one more question here. Could you please let me know. We are building a dashboard with a set of widgets, say 10-15, and say that end user changes the layout of the widgets, the order of position of the widgets.
Now we want to retain the new layout of the user, when he comes back again to our web site dashboard. The idea is we want to save the layout settings in the database / browser local storage, and want to apply the same layout again for user.

It would be great, if you could guide us on how to achieve this functionality.

Thanks in advance.

**Comment by Dilatorily** [comment]
You can listen to the end of a drag event and use the [`getItemElements`](http://packery.metafizzy.co/methods.html#getitemelements) to get the list of elements.

It would be similar to [this](http://packery.metafizzy.co/draggable.html#item-order).

```javascript
$scope.$on($paEvents.DRAGGED, function(event, hash, packery) {
  var elements = packery.getItemElements();
  var order = elements.map(function(element) {
    // Find a unique identifier 
    return element.id;
  });
  // Do something with the order array
  localStorage.setItem('order', JSON.stringify(order));
});
```

To load it back you would need to assign the ordered items in your `$scope.items`.

You may get into issues where it's not in the exact same position as what the user left it at. It's out of scope of this library, but you could possibly save the position (offsetX, offsetY) and reapply it as CSS with `position: absolute;`.

**Comment by chennas** [comment]
Thanks, it worked.
