### ISSUE TITLE
Can we have control on each of the pa-packery-item

### ISSUE THREAD

**Issue by chennas** [Dilatorily/packery-angular#6]
Hi,

I would like to know, is there any settings or property exposed by this library, whether to have granular control for each of the pa-packery-item.

Let's say that I have 10 blocks (Widgets) pa-packery-items, out of them, I want to pin few widgets, and few should be drag gable, like how we see pinned post in facebook. I tried with isDraggable option, but the settings are applied for all the items in the packery instance.

Please let me know, is this can be achievable with this directive or suggest some alternatives.

Thanks in advance.

**Comment by Dilatorily** [comment]
Please look at the [`stamp`](http://packery.metafizzy.co/methods.html#stamp) method.
